#!/usr/bin/ruby

# TODO
# - support colors: https://stackoverflow.com/a/1489233/4112863
# - install with gem: https://stackoverflow.com/a/18294746/4112863
# - auto-completion
# - how to include other Runfiles: with `require`
# - note about implicit returns
# - how to pass parameters: #{ARGV.slice(1..).join(' ')}
# - better handle CTRL+C from `shell` command

VERSION = "0.1.1"

@tasks = Hash.new

# Define a task.
def task(name, help = "", &block)
  if !name.is_a?(Symbol)
    puts "first task parameter must be a symbol"
    exit 1
  end
  if !help.is_a?(String)
    puts "second task parameter must be a string"
    exit 1
  end
  @tasks.store(name, { :help => help, :block => block })
end

# Call a task.
def call(name)
  @tasks[name][:block].call
end

# Run a shell command that will fail the tasks if it fails itself. It also add the
# ability to interect with the command, contrary to backticks syntax.
def shell(command)
  puts
  puts "> #{command}"
  puts
  if system(command) === false
    exit 1
  end
end

##########################################################################################

RUNFILE = "Runfile.rb"

if !File.exists?(RUNFILE)
  puts "#{RUNFILE} does not exist"
  exit 1
end

require "./#{RUNFILE}"

##########################################################################################

# Show the help screen if there is no provided task, or if it's explicitly requested.
if ARGV.size == 0 || (ARGV.size == 1 && ARGV[0] == "help")
  puts
  puts " run v#{VERSION}"
  puts
  @tasks.sort.to_h.each do |name, task|
    puts " #{name}#{" " * (35 - name.size)}#{task[:help]}"
  end
  exit
end

# Run the requested tasks.
name = ARGV[1].to_sym
if !@tasks.include?(name)
  puts "Unknown '#{name}' task"
  exit 1
end
call name
